### PR TITLE
Added homebrew cask file

### PR DESCRIPTION
**Pull request by arkeane**
As requested in Issue #3  I've added the ruby file that defines the cask, this needs to be sent to homebrew repository following this [guide](https://docs.brew.sh/Adding-Software-to-Homebrew#casks)

### CODE REVIEW

**Comment by arkeane** [comment]
I edited the cask file to pass the required check
`brew audit --new --cask jordanbaird-ice`
and I changed the cask token to a more descriptive one.
The file was also styled with
`brew style --fix jordanbaird-ice`

It is now ready for submission i think

**Comment by jordanbaird** [comment]
Could you change the description to just say "Powerful menu bar manager for macOS"? Other than that, I think it looks good!

**Comment by arkeane** [comment]
Done

**Comment by jordanbaird** [comment]
Great! I'll work on getting this sent to Homebrew.

**Pull request merged**
