### PR TITLE
Let Ice work without the screen recording permission

### PR DESCRIPTION
**Pull request by michyprima**
Implements #75

### CODE REVIEW

**Comment by jordanbaird** [comment]
Please run SwiftLint and make sure there are no warnings or errors.

**Comment by michyprima** [comment]
Done! Sorry about that.

**Comment by jordanbaird** [comment]
This is still pretty incomplete. Do you mind if I make changes?

**Comment by michyprima** [comment]
Of course, you definitely don't need my permission, use my code as your own

**Pull request merged**
