### PR TITLE
Update FREQUENT_ISSUES.md and format README

### PR DESCRIPTION
**Pull request by Olshansk**
See this ticket for more details: https://github.com/jordanbaird/Ice/issues/201

### CODE REVIEW

**Comment by hwamil** [comment]
Tried this, but doesn't work. Still getting same message after reverting to hidden menu bar

**Comment by jordanbaird** [comment]
@hwamil This won't permanently fix the problem – it only works while the menu bar is visible. This PR is simply explaining how to temporarily show the menu bar so that you can make the changes you need.

**Comment by jordanbaird** [comment]
@Olshansk Can we move this into `FREQUENT_ISSUES.md`? I don't want to clutter up the README too much. Maybe we can add a link to `FREQUENT_ISSUES.md` in the README. I've updated `main` since this PR, so you'll have to pull the changes into your branch.

**Comment by Olshansk** [comment]
@jordanbaird Done.

**Comment by jordanbaird** [comment]
@Olshansk Great! Thanks!

**Pull request merged**
